import type { NextPage } from 'next';
import Head from 'next/head';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import Header from './components/header';
import Banner from './banner';
import AboutUs from './aboutUs';
import Infometrics from './infometrics';

export default function Home() {
    return (
      <>
        <Head>
          <title>RainbowKit App</title>
          <meta
            content="Generated by @rainbow-me/create-rainbowkit"
            name="description"
          />
          <link href="/favicon.ico" rel="icon" />
        </Head>
        <body>
          <Banner />
          <Infometrics />
          <AboutUs />
        </body>
      </>
    )
}